framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: '%env(DOMAIN_MAILER_FROM)%'
        headers:
            From: '%env(APP_NAME)% <%env(DOMAIN_MAILER_FROM)%>'